### ISSUE TITLE
FYI: Latest patch from mo271 for libjxl 0.9.0

### ISSUE THREAD

**Issue by antermin** [Alex313031/thorium-libjxl#19]
https://chromium-review.googlesource.com/c/chromium/src/+/5163728

**Comment by Alex313031** [comment]
@antermin Will probably use this or 0.82 stable. Might fix https://github.com/Alex313031/thorium-libjxl/issues/18

**Comment by Alex313031** [comment]
@antermin I am using 0.9.0 in the M120 release.
