### ISSUE TITLE
The HDR metadata of the JXL image is not being utilized.

### ISSUE THREAD

**Issue by lns103** [Alex313031/thorium-libjxl#24]
I exported the same HDR image in AVIF and JXL formats using Adobe Camera Raw, but noticed color differences in Thorium. After investigation, I found that removing the brightness metadata from AVIF results in a display consistent with JXL.
I have confirmed that JXL contains brightness metadata using ExifTool.
I used ```ffmpeg -i hdr_metadata.avif -c copy no_hdr_metadata.avif``` to remove brightness metadata from the AVIF file.
```
CCV Primaries XY                : 0.7079,0.2920,0.1700,0.7970,0.1310,0.0460
CCV White XY                    : 0.3127,0.3290
CCV Min Luminance Nits          : 0.584496
CCV Max Luminance Nits          : 818.571806
CCV Avg Luminance Nits          : 89.355415
```
[test_sample.zip](https://github.com/Alex313031/thorium-libjxl/files/14348263/test_sample.zip)

~~And this may help to fix~~. https://chromium-review.googlesource.com/c/chromium/src/+/4020332
This patch is from the Chromium team to add support for HDR metadata in AVIF. I haven't found any similar patches for JXL.

**Comment by gz83** [comment]
It may also be related to this issue. In addition, the patch you provided has already been included in Thorium. This is a patch that has been merged quite early.

https://github.com/Alex313031/thorium-libjxl/issues/18

@lns103

**Comment by lns103** [comment]
> In addition, the patch you provided has already been included in Thorium. This is a patch that has been merged quite early.

This patch only affects AVIF images.

**Comment by lns103** [comment]
Regarding https://github.com/Alex313031/thorium-libjxl/issues/18, I believe it is caused by differences in Chromium's tone-mapping algorithm compared to other software. After re-exporting that image using Adobe Camera Raw, the highlights in the image became brighter.
From my observations, the absence of brightness metadata in Chromium seems to result in a darker display, possibly because Chromium defaults to a peak brightness of 10000 nits for PQ content.

**Comment by gz83** [comment]
Could you please take a look at this issue and another issue?

another issue: https://github.com/Alex313031/thorium-libjxl/issues/18

Thorium currently uses version 0.9.2 of libjxl

@mo271
