### ISSUE TITLE
FYI: New, Fresh patch from mo271 for libjxl 0.10.2

### ISSUE THREAD

**Issue by antermin** [Alex313031/thorium-libjxl#27]
@mo271 has made a new patch for Chrome: https://chromium-review.googlesource.com/c/chromium/src/+/5454316

This is a fresh one and different than the previous ones (4255409, 5163728).

**Comment by gz83** [comment]
We will update libjxl regularly, but there is no rush

**Comment by Alex313031** [comment]
@antermin We already updated to 0.10.2 before he did, but he also added some more fixes, so I will merge his patches here.
