### ISSUE TITLE
Use permissive licence?

### ISSUE THREAD

**Issue by FoxtrotCZ** [Alex313031/thorium-libjxl#8]
Hello,
would it be possible to change licence of this project to permissive one so it can be used by more people and non-GPL projects?
For example use [BSD 3-Clause "New" or "Revised" License](https://choosealicense.com/licenses/bsd-3-clause/) which is licence used by [libjxl](https://github.com/libjxl/libjxl).
Thanks for consideration.

**Comment by Alex313031** [comment]
@goodusername123 @FoxtrotCZ There you go > https://github.com/Alex313031/thorium-libjxl/commit/aa6b1603c5efd7b371f607fd2be736dedb11a8a8
